-- Migration 010: Discord Restructure
-- Adds discord_thread_id to admin_requests for bidirectional sync
-- Adds admin_regions table for regional admin assignments (country/state level)
-- Safe to run multiple times (IF NOT EXISTS / IF NOT EXISTS patterns)

-- 1. Track Discord thread ID on admin requests for bidirectional sync
ALTER TABLE admin_requests ADD COLUMN IF NOT EXISTS discord_thread_id TEXT;

-- 2. Regional admin region assignments (country/state level)
CREATE TABLE IF NOT EXISTS admin_regions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES admin_users(user_id) ON DELETE CASCADE,
    country TEXT NOT NULL,
    state_region TEXT,              -- NULL = whole country, set = specific state/province
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    assigned_by TEXT,
    UNIQUE (user_id, country, state_region)
);
CREATE INDEX IF NOT EXISTS idx_admin_regions_user ON admin_regions(user_id);
CREATE INDEX IF NOT EXISTS idx_admin_regions_country ON admin_regions(country);
