-- DigiLab - Digimon TCG Tournament Tracker
-- Database Schema for PostgreSQL (Neon)
-- Version: 1.8.0
-- Created: January 2026
-- Updated: 2026-03-15 - Discord restructure: admin_regions, discord_thread_id on requests

-- =============================================================================
-- EXTENSIONS
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;  -- Trigram fuzzy matching for duplicate detection

-- =============================================================================
-- SCENES TABLE
-- Hierarchical geographic organization (Global -> Country -> State -> Metro)
-- Enables multi-region support and deep linking with ?scene=slug URLs
-- =============================================================================
CREATE TABLE IF NOT EXISTS scenes (
    scene_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    slug VARCHAR UNIQUE,              -- URL-friendly identifier (e.g., 'dfw', 'online')
    display_name VARCHAR,             -- Human-readable name (e.g., 'Dallas-Fort Worth')
    parent_scene_id INTEGER REFERENCES scenes(scene_id) ON DELETE SET NULL,
    scene_type VARCHAR NOT NULL,      -- 'global', 'country', 'state', 'metro', 'online'
    latitude DECIMAL(9, 6),           -- Center point for map views
    longitude DECIMAL(9, 6),
    discord_thread_id TEXT,           -- Discord #scene-coordination thread ID for webhook routing
    country TEXT,                     -- Auto-populated from reverse geocode
    state_region TEXT,                -- Auto-populated from reverse geocode
    continent TEXT,                  -- Continent code for cascading selector (e.g., 'north_america')
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT                   -- Admin username who last modified
);

-- Create indexes for scene queries
CREATE INDEX IF NOT EXISTS idx_scenes_slug ON scenes(slug);
CREATE INDEX IF NOT EXISTS idx_scenes_parent ON scenes(parent_scene_id);
CREATE INDEX IF NOT EXISTS idx_scenes_type ON scenes(scene_type);

-- =============================================================================
-- STORES TABLE
-- Tracks local game stores hosting Digimon TCG events
-- =============================================================================
CREATE TABLE IF NOT EXISTS stores (
    store_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    slug VARCHAR,                     -- URL-friendly identifier for deep linking
    address VARCHAR,
    city VARCHAR NOT NULL,
    state VARCHAR,
    zip_code VARCHAR,
    latitude DECIMAL(9, 6),
    longitude DECIMAL(9, 6),
    scene_id INTEGER REFERENCES scenes(scene_id) ON DELETE SET NULL,
    schedule_info TEXT,               -- Legacy: JSON stored as text (use store_schedules instead)
    tcgplus_store_id VARCHAR,
    website VARCHAR,
    phone VARCHAR,
    is_active BOOLEAN DEFAULT TRUE,
    is_online BOOLEAN DEFAULT FALSE,
    country VARCHAR DEFAULT 'USA',        -- Country code for international support
    limitless_organizer_id INTEGER,  -- Limitless TCG organizer ID for auto-sync
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT                   -- Admin username who last modified
);

-- Create index for store slug lookups
CREATE INDEX IF NOT EXISTS idx_stores_slug ON stores(slug);
CREATE INDEX IF NOT EXISTS idx_stores_scene ON stores(scene_id);
CREATE INDEX IF NOT EXISTS idx_stores_limitless ON stores(limitless_organizer_id);

-- =============================================================================
-- STORE SCHEDULES TABLE
-- Tracks recurring event schedules for stores (e.g., "Wednesdays at 7pm")
-- One row per day/time slot - stores with multiple events have multiple rows
-- =============================================================================
CREATE TABLE IF NOT EXISTS store_schedules (
    schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INTEGER NOT NULL REFERENCES stores(store_id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL,       -- 0=Sunday, 1=Monday, ..., 6=Saturday
    start_time TEXT NOT NULL,           -- "19:00" format (24-hour)
    frequency VARCHAR DEFAULT 'weekly', -- weekly, biweekly, monthly
    week_of_month TEXT,               -- '1st', '2nd', '3rd', '4th', 'last' (monthly only)
    next_occurrence DATE,             -- Anchor date for biweekly patterns
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for schedule queries
CREATE INDEX IF NOT EXISTS idx_store_schedules_store ON store_schedules(store_id);
CREATE INDEX IF NOT EXISTS idx_store_schedules_day ON store_schedules(day_of_week);
CREATE INDEX IF NOT EXISTS idx_store_schedules_active ON store_schedules(is_active);

-- =============================================================================
-- FORMATS TABLE
-- Reference table for game formats/sets (BT19, EX08, etc.)
-- =============================================================================
CREATE TABLE IF NOT EXISTS formats (
    format_id VARCHAR PRIMARY KEY,           -- Set code: 'BT19', 'EX08', etc.
    set_name VARCHAR NOT NULL,               -- Full name: 'Xros Encounter'
    display_name VARCHAR NOT NULL,           -- Display: 'BT19 (Xros Encounter)'
    release_date DATE,                       -- Release date for sorting
    sort_order INTEGER,                      -- Manual sort order (lower = newer)
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for format lookups
CREATE INDEX IF NOT EXISTS idx_formats_active ON formats(is_active);
CREATE INDEX IF NOT EXISTS idx_formats_sort ON formats(sort_order);

-- =============================================================================
-- CARDS TABLE
-- Cached card data from DigimonCard.io API for local search
-- =============================================================================
CREATE TABLE IF NOT EXISTS cards (
    card_id VARCHAR PRIMARY KEY,          -- e.g., "BT13-087"
    name VARCHAR NOT NULL,                -- e.g., "Beelzemon"
    display_name VARCHAR NOT NULL,        -- e.g., "Beelzemon (BT13-087)"
    card_type VARCHAR NOT NULL,           -- "Digimon", "Tamer", "Option", "Digi-Egg"
    color VARCHAR,                        -- Primary color
    color2 VARCHAR,                       -- Secondary color (if any)
    level INTEGER,                        -- Digimon level (NULL for others)
    dp INTEGER,                           -- Digimon DP (NULL for others)
    play_cost INTEGER,
    digi_type VARCHAR,                    -- e.g., "Demon Lord"
    stage VARCHAR,                        -- e.g., "Mega"
    rarity VARCHAR,                       -- e.g., "SR"
    set_code VARCHAR,                     -- e.g., "BT13" (extracted from card_id)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for card lookups
CREATE INDEX IF NOT EXISTS idx_cards_name ON cards(name);
CREATE INDEX IF NOT EXISTS idx_cards_type ON cards(card_type);
CREATE INDEX IF NOT EXISTS idx_cards_color ON cards(color);
CREATE INDEX IF NOT EXISTS idx_cards_set ON cards(set_code);

-- =============================================================================
-- PLAYERS TABLE
-- Tracks players participating in local tournaments
-- =============================================================================
CREATE TABLE IF NOT EXISTS players (
    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR NOT NULL,
    slug VARCHAR,                    -- URL-safe slug derived from display_name
    tcgplus_id VARCHAR,
    member_number VARCHAR,  -- Bandai TCG+ member number (0000XXXXXX)
    limitless_username VARCHAR,
    home_store_id INTEGER REFERENCES stores(store_id) ON DELETE SET NULL,
    identity_status VARCHAR DEFAULT 'unverified',  -- 'verified' (has Bandai ID/Limitless), 'unverified' (scene-locked)
    home_scene_id INTEGER REFERENCES scenes(scene_id) ON DELETE SET NULL,  -- Scoping for unverified players
    is_active BOOLEAN DEFAULT TRUE,
    is_anonymized BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT                   -- Admin username who last modified
);

-- Create index for player lookups
CREATE INDEX IF NOT EXISTS idx_players_display_name ON players(display_name);
CREATE INDEX IF NOT EXISTS idx_players_slug ON players(slug) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_players_tcgplus_id ON players(tcgplus_id);
CREATE INDEX IF NOT EXISTS idx_players_identity_status ON players(identity_status);
CREATE INDEX IF NOT EXISTS idx_players_home_scene ON players(home_scene_id);
CREATE INDEX IF NOT EXISTS idx_players_member_number ON players(member_number) WHERE member_number IS NOT NULL AND member_number != '';

-- Unique index on member_number (partial — only non-NULL, non-empty values)
CREATE UNIQUE INDEX IF NOT EXISTS idx_players_unique_member_number
  ON players (member_number) WHERE member_number IS NOT NULL AND member_number != '';

-- =============================================================================
-- DECK ARCHETYPES TABLE
-- Reference table mapping community deck names to associated cards
-- =============================================================================
CREATE TABLE IF NOT EXISTS deck_archetypes (
    archetype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archetype_name VARCHAR NOT NULL UNIQUE,
    slug VARCHAR,                     -- URL-friendly identifier for deep linking
    display_card_id VARCHAR,
    primary_color VARCHAR NOT NULL,
    secondary_color VARCHAR,
    playstyle_tags TEXT,              -- JSON array stored as text
    is_active BOOLEAN DEFAULT TRUE,
    is_multi_color BOOLEAN DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT                   -- Admin username who last modified
);

-- Create indexes for archetype lookups
CREATE INDEX IF NOT EXISTS idx_archetypes_name ON deck_archetypes(archetype_name);
CREATE INDEX IF NOT EXISTS idx_archetypes_slug ON deck_archetypes(slug);
CREATE INDEX IF NOT EXISTS idx_archetypes_color ON deck_archetypes(primary_color);

-- =============================================================================
-- ARCHETYPE CARDS TABLE (Junction Table)
-- Links archetypes to their associated cards from DigimonCard.io
-- =============================================================================
CREATE TABLE IF NOT EXISTS archetype_cards (
    archetype_id INTEGER NOT NULL REFERENCES deck_archetypes(archetype_id) ON DELETE CASCADE,
    card_id VARCHAR NOT NULL,
    card_role VARCHAR NOT NULL,
    is_core BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (archetype_id, card_id)
);

-- Create index for card lookups (find decks using a specific card)
CREATE INDEX IF NOT EXISTS idx_archetype_cards_card_id ON archetype_cards(card_id);

-- =============================================================================
-- DECK REQUESTS TABLE
-- Tracks pending deck archetype requests from public submissions
-- =============================================================================
CREATE TABLE IF NOT EXISTS deck_requests (
    request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_name TEXT NOT NULL,
    primary_color TEXT NOT NULL,
    secondary_color TEXT,
    display_card_id TEXT,
    status TEXT DEFAULT 'pending',  -- pending, approved, rejected, needs_classification
    approved_archetype_id INTEGER,  -- Links to created deck after approval
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    -- Classification review fields (added for auto-classification workflow)
    suggested_archetype_name VARCHAR,  -- What classification thought it was (may not exist in DB yet)
    decklist_json TEXT,                -- The actual card list for admin review
    source VARCHAR DEFAULT 'manual',   -- 'manual', 'limitless_sync', 'classification'
    result_id INTEGER                  -- Link back to result for updating after approval
);

-- Create index for pending requests lookup
CREATE INDEX IF NOT EXISTS idx_deck_requests_status ON deck_requests(status);

-- =============================================================================
-- TOURNAMENTS TABLE
-- Tracks individual tournament events
-- =============================================================================
CREATE TABLE IF NOT EXISTS tournaments (
    tournament_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INTEGER NOT NULL REFERENCES stores(store_id) ON DELETE RESTRICT,
    event_date DATE NOT NULL,
    event_type VARCHAR NOT NULL,
    format VARCHAR,
    player_count INTEGER,
    rounds INTEGER,
    limitless_id VARCHAR,
    record_format TEXT DEFAULT 'points',  -- 'points' or 'wlt' — how results were entered
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT                   -- Admin username who last modified
);

-- Create indexes for tournament queries
CREATE INDEX IF NOT EXISTS idx_tournaments_store ON tournaments(store_id);
CREATE INDEX IF NOT EXISTS idx_tournaments_date ON tournaments(event_date);
CREATE INDEX IF NOT EXISTS idx_tournaments_type ON tournaments(event_type);

-- =============================================================================
-- RESULTS TABLE
-- Tracks player results for each tournament
-- =============================================================================
CREATE TABLE IF NOT EXISTS results (
    result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(tournament_id) ON DELETE CASCADE,
    player_id INTEGER NOT NULL REFERENCES players(player_id) ON DELETE RESTRICT,
    archetype_id INTEGER REFERENCES deck_archetypes(archetype_id) ON DELETE SET NULL,
    pending_deck_request_id INTEGER REFERENCES deck_requests(request_id) ON DELETE SET NULL,
    placement INTEGER,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0,
    ties INTEGER DEFAULT 0,
    points INTEGER,        -- Original points value as entered (NULL for WLT-entered results)
    decklist_url VARCHAR,  -- Link to external decklist (DeckLog, digimonmeta, etc.)
    decklist_json TEXT,  -- JSON stored as text (for future full decklist storage)
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tournament_id, player_id)
);

-- Create indexes for result queries
CREATE INDEX IF NOT EXISTS idx_results_tournament ON results(tournament_id);
CREATE INDEX IF NOT EXISTS idx_results_player ON results(player_id);
CREATE INDEX IF NOT EXISTS idx_results_archetype ON results(archetype_id);
CREATE INDEX IF NOT EXISTS idx_results_placement ON results(placement);
CREATE INDEX IF NOT EXISTS idx_results_pending_deck ON results(pending_deck_request_id);

-- =============================================================================
-- MATCHES TABLE
-- Tracks round-by-round match data from match history screenshots
-- Note: If both players submit match history, we'll have two rows for the
-- same match (from each perspective). This is intentional for simplicity.
-- =============================================================================
CREATE TABLE IF NOT EXISTS matches (
    match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(tournament_id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL,
    player_id INTEGER NOT NULL REFERENCES players(player_id) ON DELETE RESTRICT,
    opponent_id INTEGER NOT NULL REFERENCES players(player_id) ON DELETE RESTRICT,
    games_won INTEGER NOT NULL DEFAULT 0,
    games_lost INTEGER NOT NULL DEFAULT 0,
    games_tied INTEGER NOT NULL DEFAULT 0,
    match_points INTEGER NOT NULL DEFAULT 0,  -- 3=win, 1=draw, 0=loss
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tournament_id, round_number, player_id)
);

-- Create indexes for match queries
CREATE INDEX IF NOT EXISTS idx_matches_tournament ON matches(tournament_id);
CREATE INDEX IF NOT EXISTS idx_matches_player ON matches(player_id);
CREATE INDEX IF NOT EXISTS idx_matches_opponent ON matches(opponent_id);

-- =============================================================================
-- DATA INGESTION LOG TABLE
-- Tracks API calls and data imports for debugging
-- =============================================================================
CREATE TABLE IF NOT EXISTS ingestion_log (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR NOT NULL,
    action VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    records_affected INTEGER DEFAULT 0,
    error_message TEXT,
    metadata TEXT,  -- JSON stored as text
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- PLAYER RATINGS CACHE TABLE
-- Pre-computed player ratings for performance (recomputed on result submission)
-- =============================================================================
CREATE TABLE IF NOT EXISTS player_ratings_cache (
    player_id INTEGER PRIMARY KEY,
    competitive_rating INTEGER NOT NULL DEFAULT 1500,
    achievement_score INTEGER NOT NULL DEFAULT 0,
    events_played INTEGER NOT NULL DEFAULT 0,
    last_computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- STORE RATINGS CACHE TABLE
-- Pre-computed store ratings for performance (recomputed on result submission)
-- =============================================================================
CREATE TABLE IF NOT EXISTS store_ratings_cache (
    store_id INTEGER PRIMARY KEY,
    avg_player_rating INTEGER NOT NULL DEFAULT 1500,
    last_computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- PLAYER RATING HISTORY TABLE
-- Tracks player rating changes per tournament for history graphs
-- Used by single-pass chronological rating calculation
-- =============================================================================
CREATE TABLE IF NOT EXISTS player_rating_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(player_id) ON DELETE CASCADE,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(tournament_id) ON DELETE CASCADE,
    rating_before INTEGER NOT NULL,
    rating_after INTEGER NOT NULL,
    rating_change INTEGER NOT NULL,
    events_played INTEGER NOT NULL,  -- Number of events played up to and including this one
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(player_id, tournament_id)
);

CREATE INDEX IF NOT EXISTS idx_rating_history_player ON player_rating_history(player_id);
CREATE INDEX IF NOT EXISTS idx_rating_history_tournament ON player_rating_history(tournament_id);
CREATE INDEX IF NOT EXISTS idx_rating_history_player_event ON player_rating_history(player_id, tournament_id);

-- =============================================================================
-- RATING SNAPSHOTS TABLE
-- Historical ratings frozen at the end of each format era
-- =============================================================================
CREATE TABLE IF NOT EXISTS rating_snapshots (
    player_id INTEGER NOT NULL,
    format_id VARCHAR NOT NULL,
    competitive_rating INTEGER NOT NULL DEFAULT 1500,
    achievement_score INTEGER NOT NULL DEFAULT 0,
    events_played INTEGER NOT NULL DEFAULT 0,
    player_rank INTEGER,
    snapshot_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, format_id)
);

CREATE INDEX IF NOT EXISTS idx_rating_snapshots_format ON rating_snapshots(format_id);

-- =============================================================================
-- LIMITLESS DECK MAP TABLE
-- Maps Limitless TCG deck archetype identifiers to local deck_archetypes
-- Populated during sync; unmapped decks create deck_requests for admin review
-- =============================================================================
CREATE TABLE IF NOT EXISTS limitless_deck_map (
    limitless_deck_id VARCHAR NOT NULL PRIMARY KEY,  -- e.g., "imperialdramon"
    limitless_deck_name VARCHAR,                     -- Human-readable name from Limitless
    archetype_id INTEGER REFERENCES deck_archetypes(archetype_id) ON DELETE SET NULL
);

-- =============================================================================
-- LIMITLESS SYNC STATE TABLE
-- Tracks per-organizer sync progress for incremental imports
-- =============================================================================
CREATE TABLE IF NOT EXISTS limitless_sync_state (
    organizer_id INTEGER NOT NULL PRIMARY KEY,       -- Limitless organizer ID
    last_synced_at TIMESTAMP,                        -- When sync last ran
    last_tournament_date TIMESTAMP,                  -- Most recent tournament date synced
    tournaments_synced INTEGER DEFAULT 0             -- Total tournaments imported
);

-- =============================================================================
-- ADMIN USERS TABLE
-- Per-user admin accounts with bcrypt password hashes and role-based access
-- Replaces shared ADMIN_PASSWORD/SUPERADMIN_PASSWORD env vars
-- =============================================================================
CREATE TABLE IF NOT EXISTS admin_users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    discord_user_id TEXT,             -- Discord numeric user ID for @mentions in webhooks
    role TEXT NOT NULL DEFAULT 'scene_admin',
    scene_id INTEGER REFERENCES scenes(scene_id) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_users_username ON admin_users(username);

-- =============================================================================
-- ADMIN USER SCENES TABLE (Junction Table)
-- Many-to-many relationship between admins and scenes
-- Replaces 1:1 scene_id on admin_users for multi-scene assignments
-- =============================================================================
CREATE TABLE IF NOT EXISTS admin_user_scenes (
    user_id INTEGER NOT NULL REFERENCES admin_users(user_id) ON DELETE CASCADE,
    scene_id INTEGER NOT NULL REFERENCES scenes(scene_id) ON DELETE CASCADE,
    is_primary BOOLEAN DEFAULT FALSE,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    assigned_by TEXT,
    PRIMARY KEY (user_id, scene_id)
);

CREATE INDEX IF NOT EXISTS idx_admin_user_scenes_scene ON admin_user_scenes(scene_id);
CREATE INDEX IF NOT EXISTS idx_admin_user_scenes_user ON admin_user_scenes(user_id);

-- =============================================================================
-- ADMIN REQUESTS TABLE
-- Unified request queue for store requests, scene requests, data errors, bugs
-- =============================================================================
CREATE TABLE IF NOT EXISTS admin_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type TEXT NOT NULL,              -- 'store_request', 'scene_request', 'data_error', 'bug_report'
    scene_id INTEGER REFERENCES scenes(scene_id),
    status TEXT NOT NULL DEFAULT 'pending',  -- pending, approved, rejected, resolved
    payload JSONB NOT NULL,                  -- flexible per request type
    discord_username TEXT NOT NULL,
    discord_thread_id TEXT,                  -- Discord forum thread ID for bidirectional sync
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolved_by TEXT,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_admin_requests_status ON admin_requests(status);
CREATE INDEX IF NOT EXISTS idx_admin_requests_type ON admin_requests(request_type);
CREATE INDEX IF NOT EXISTS idx_admin_requests_scene ON admin_requests(scene_id);

-- =============================================================================
-- ADMIN REGIONS TABLE
-- Regional admin assignments at country/state level
-- Enables regional_admin role to inherit coverage over multiple scenes
-- =============================================================================
CREATE TABLE IF NOT EXISTS admin_regions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES admin_users(user_id) ON DELETE CASCADE,
    country TEXT NOT NULL,
    state_region TEXT,              -- NULL = whole country, set = specific state/province
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    assigned_by TEXT
);
-- Use COALESCE for unique constraint since NULL != NULL in PostgreSQL
CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_regions_unique
  ON admin_regions(user_id, country, COALESCE(state_region, ''));

CREATE INDEX IF NOT EXISTS idx_admin_regions_user ON admin_regions(user_id);
CREATE INDEX IF NOT EXISTS idx_admin_regions_country ON admin_regions(country);

-- =============================================================================
-- ANNOUNCEMENTS TABLE
-- App-wide announcements with type and optional expiry
-- =============================================================================
CREATE TABLE IF NOT EXISTS announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    announcement_type TEXT NOT NULL DEFAULT 'info',  -- info, donation, update, event
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ  -- NULL = no expiry
);

-- =============================================================================
-- MATERIALIZED VIEWS (pre-computed aggregations for performance)
-- See db/migrations/005_materialized_views.sql for full definitions.
-- Refresh via: refresh_materialized_views() in shared-server.R
-- =============================================================================
-- mv_player_store_stats   — grain: (player_id, store_id, format, archetype_id)
-- mv_archetype_store_stats — grain: (archetype_id, store_id, format, event_type, week_start)
-- mv_tournament_list      — grain: (tournament_id)
-- mv_store_summary        — grain: (store_id)
-- mv_dashboard_counts     — grain: (scene_id, format, event_type, is_online)
